shell.nix: Add vendorSha256 attr to go modules
This fixes the following error, discovered on a fresh install of nix on
Linux:

```
error: while evaluating the attribute 'buildInputs' of the derivation 'waypoint' at /home/hicks/workspace/git/github.com/hashicorp/waypoint/shell.nix:83:3:
while evaluating 'getOutput' at /nix/store/5sg4ww1hmh574swgrsr6kr6i82cfgng4-nixpkgs-21.03pre243353.6d4b93323e7/nixpkgs/lib/attrsets.nix:464:23, called from undefined position:
while evaluating anonymous function at /nix/store/5sg4ww1hmh574swgrsr6kr6i82cfgng4-nixpkgs-21.03pre243353.6d4b93323e7/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:143:17, called from undefined position:
anonymous function at /nix/store/5sg4ww1hmh574swgrsr6kr6i82cfgng4-nixpkgs-21.03pre243353.6d4b93323e7/nixpkgs/pkgs/development/go-modules/generic/default.nix:3:1 called without required argument 'vendorSha256', at /home/hicks/workspace/git/github.com/hashicorp/waypoint/shell.nix:21:17
```